name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-fds:
    runs-on: [self-hosted, Linux, X64, live]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Deploy with Docker Compose
        run: |
          cp -rf /var/www/public/shahzad-fabrics/.env.master .env
          chmod +x build.sh
          ./build.sh
